### PR TITLE
Ifstringsarerotated

### LINKED ISSUE #66: If Strings are rotated
Two strings are given and we have to check if they are rotation of each other or not. 
Expected Time Complexity: O(1).
Expected Space Complexity: O(N)

### PR DESCRIPTION
**Pull request by Abhishek-Sood**
resolved issue #66

### CODE REVIEW

**Comment by Abhishek-Sood** [comment]
idk sir why this gas station DSA file is being shown in changes

**Comment by ken1000minus7** [comment]
Add it back in this branch

**Comment by Abhishek-Sood** [comment]
i cant when i was cloning the repo to my desktop the file was showing errors

**Comment by ken1000minus7** [comment]
Just create a file with the same name and copy paste the code

**Comment by Abhishek-Sood** [comment]
i have created an other pull request for that issue

**Comment by ken1000minus7** [comment]
That issue is already resolved....you don't need to make pr for it, just add the deleted file back in this branch

**Pull request closed without merging**
