### PR TITLE
IPL Teams #162

### LINKED ISSUE #162: IPL Teams
### **IPL TEAMS**

Create an HTML Page displaying a **table containing the list of all 10 IPL teams** (in alphabetical order). The table should consist:

- A **heading** having text **_'IPL TEAMS'_** in stylized text.
- **3 Columns** representing **serial number, team name and team logo**.
-  **Label** of each column.
- The **team name field should be clickable** and should load the Wikipedia page of the team on clicking.
- Proper **styling and sizing** of all text and images.

**Reference:** https://en.wikipedia.org/wiki/Indian_Premier_League#Teams

**Hint:** HTML, CSS

### PR DESCRIPTION
**Pull request by Dharya4242**
Resolved #162

### CODE REVIEW

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
Hey @Dharyaj11 your code is incomplete and it appears that this code is written by chatgpt, while chatgpt is great as a learning tool, please refrain from directly copying code from there in the future and instead try to develop your skills by writing your own code or seeking guidance. I won't be merging this right now, please try to rewrite the code yourself

**Comment by Dharya4242** [comment]
I am really sorry sir .
sir i know how to write in html but i dont know about css, so i only copied css part only , i wil learn css side by side.

**Comment by ken1000minus7** [comment]
@Dharyaj11 any updates?

**Comment by Dharya4242** [comment]
Sry sir meri holi ke baad se tabiyat khrab thi isliye nhi kuch kra😓

**Pull request merged**
