### PR TITLE
Issue#11DSA arrange stack in decreasing order

### LINKED ISSUE #11: SORT the stack recursively in decreasing order
#DSA
Given a Stack 'S'. Write a Python Program to SORT the stack recursively in decreasing order. Note: Looping through stack is not allowed. You need to return a stack that is sorted in decreasing order.
Example:
Given stack: 
5 1 2 6 4 
Output:
6 5 4 2 1

### PR DESCRIPTION
**Pull request by AkankshaNarula**
Resolved Issue #11

### CODE REVIEW

**Comment by harshjohar** [comment]
Again there are two issues in a single PR. DO NO DO THIS.

One issue at a time.

**Comment by AkankshaNarula** [comment]
@harshjohar sir its only issue 11 Stack in dec order I hv only changed the folder for issue24

**Comment by harshjohar** [comment]
ohh

**Review by harshjohar — COMMENTED** [review]
lgtm

**Pull request merged**
