### PR TITLE
Two sum #23

### LINKED ISSUE #23: Two Sum
# DSA

Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

 

Example 1:

Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].
Example 2:

Input: nums = [3,2,4], target = 6
Output: [1,2]
Example 3:

Input: nums = [3,3], target = 6
Output: [0,1]
 

Constraints:

1.  2 <= nums.length <= 104
2.  -109 <= nums[i] <= 109
3.  -109 <= target <= 109
4.  Only one valid answer exists.
 

Follow-up: Can you come up with an algorithm that is less than O(n2) time complexity?

### PR DESCRIPTION
**Pull request by Dharya4242**
Resolved issue #23

### CODE REVIEW

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
Your code is correct however remove files of other issues and the `hello.exe` file

**Comment by Dharya4242** [comment]
> Your code is correct however remove files of other issues and the `hello.exe` file

sir I don't know how to remove other files please tell me how to , and what is the next step if my code is correct

**Comment by ken1000minus7** [comment]
Just simply delete them for now and push the new commit

**Comment by Dharya4242** [comment]
> Just simply delete them for now and push the new commit

done sir

**Review by ken1000minus7 — APPROVED** [review]
Lgtm

**Pull request merged**
