### PR TITLE
Floor and Ceil

### LINKED ISSUE #46: Solve "Floor and Ceil"
# CP 
Problem Link: https://www.hackerrank.com/contests/testing-1669399991/challenges/floor-and-ceil-1-1

- Attach screenshot showing all testcases passed. PR will be merged only if all testcases are passed.

### PR DESCRIPTION
**Pull request by GauravGupta993**
#46

### CODE REVIEW

**Comment by GauravGupta993** [comment]
Whenever I create a PR from the branch then all the commits of the main are also shown in PR. How to avoid that? Also please refer to the last commit of Solve "Floor and Ceil" for this issue.
Floor and ceil Submission #1357147311 _ Fun Problem PEC-ACM Question _ Contests _ HackerRank - Google Chrome 03-03-2023 02_04_23

**Comment by si-ddhant** [comment]
> Whenever I create a PR from the branch then all the commits of the main are also shown in PR. How to avoid that? Also please refer to the last commit of Solve "Floor and Ceil" for this issue. Floor and ceil Submission #1357147311 _ Fun Problem PEC-ACM Question _ Contests _ HackerRank - Google Chrome 03-03-2023 02_04_23

learn and use git branching. use different branches for different issues and then pr separately for each issue.

**Comment by ken1000minus7** [comment]
For now u can delete the dsa file from this one, also u need to make a branch before u start working on an issue not after, since when u create a new branch it carries the commits of the main branch at the time, so if u solve the issue in the main branch before making a new branch, the new branch will carry commits of that issue as well

**Comment by GauravGupta993** [comment]
> For now u can delete the dsa file from this one, also u need to make a branch before u start working on an issue not after, since when u create a new branch it carries the commits of the main branch at the time, so if u solve the issue in the main branch before making a new branch, the new branch will carry commits of that issue as well

Yes sir I will keep it in mind and will keep the main branch empty and create all PRs from other branches. Please check this PR this time.

**Comment by ken1000minus7** [comment]
Just delete the other issue's file and commit the changes in this branch, rest is good

**Comment by GauravGupta993** [comment]
> Just delete the other issue's file and commit the changes in this branch, rest is good

Yes sir done. TYSM for the guidance

**Comment by ken1000minus7** [comment]
Ok so..... I just merged your other pr and since we deleted that file in this pr......we hv conflicts now😅

**Comment by ken1000minus7** [comment]
Try running `git pull origin main` , lets see if that can solve the conflict without any other probs

**Comment by GauravGupta993** [comment]
> Try running `git pull origin main` , lets see if that can solve the conflict without any other probs

I am creating branches and other stuff from github website itself and not from git bash or from windows terminal. Is there a way to enter commands through github website? Or will else adding the file again in this branch and making commit help? Or shall I close this pull req., delete this branch, create a new branch, and again create a pr for this issue?

**Comment by ken1000minus7** [comment]
You can try adding the file back, if that doesn't work then the last option is the safest one

**Comment by GauravGupta993** [comment]
> You can try adding the file back, if that doesn't work then the last option is the safest one

It seems it worked. Please confirm. Also is it possible to get 3 points for 2 PR(this one and DSA||Gas Station) Totally fine if not possible.

**Comment by ken1000minus7** [comment]
There is one point per pr unless it's of a higher difficulty

**Pull request merged**
