### PR TITLE
heartfailure #96

### PR DESCRIPTION
**Pull request by Abhishek-Sood**
issue #96

### CODE REVIEW

**Comment by Ishwarendra** [comment]
Run the last cell so we can see the output and commit again @Abhishek-Sood

**Comment by Abhishek-Sood** [comment]
Screenshot (379)

**Comment by Abhishek-Sood** [comment]
i have committed too

**Comment by SUGAM-ARORA** [comment]
Great done

**Review by SUGAM-ARORA — COMMENTED** [review]
Great done

**Comment by Abhishek-Sood** [comment]
thanks

**Pull request merged**
