### PR TITLE
Class implementing complex numbers #110

### LINKED ISSUE #110: Create a complex number class
Create a complex number class that has two properties, real and imaginary , create a constructor and functions accordingly, u can do this in any language
dk what a class is or how to make one? u can google and learn :redeyes:

### PR DESCRIPTION
**Pull request by ItsPranavz**
#110 solved.

### CODE REVIEW

**Review by harshjohar — CHANGES_REQUESTED** [review]
let's get our hands dirty, can you implement add, subtract, multiply in complex number class?

HINT:
```py
def add(complex c):
    return complex(self.real + c.real, self.imag + c.imag)
```

Similarly implement subtract and multiply

BONUS : If you can implement operator overloading here `(+, -, *)`, I ll give you two points for this issue :redeyes:

**Comment by ItsPranavz** [comment]
I like how this sounds. Challenge accepted.

Side note : I am sure you know that :redeyes: doesn't work here. Bad Discord Habit.

**Comment by ItsPranavz** [comment]
Piece of cake. I can already smell extra points. +10

**Comment by harshjohar** [comment]
lol this was too easy, wish you would have used C++, anyways, now do divide operator too, :redeyes: and yes I know redeyes doesn't work here, but habits....

**Comment by harshjohar** [comment]
I have labelled this `easy`, so you ll get two points when merged, but first make this something OP

**Review by harshjohar — CHANGES_REQUESTED** [review]
time to level up, now `/`

**Comment by harshjohar** [comment]
Do one more thing, whenever I do `print(c)`, where c is an instance of your class, it should give me the form of `a+ib` or `a-ib` whatever @ItsPranavz

**Review by harshjohar — APPROVED** [review]

**Comment by ItsPranavz** [comment]
I knew you would ask for inverse and conjugate next so I did that already.
+ Added inverse
+ Added divide
+ Added print
+ Added scalar division
+ Added conjugate.

**Comment by ItsPranavz** [comment]
Now that's OP

**Comment by harshjohar** [comment]
I have more loaded, but let's make a different issue for that
- polar form
- Euler form
- rational power
- maybe graphs?

But let's spare you for now :kek:
@ItsPranavz

**Pull request merged**
