### PR TITLE
Write JS Code for getting weather condition of a place

### LINKED ISSUE #180: Write JS Code for getting weather condition of a place
<h1> Web </h1>
The place should be the input from the user and the OpenWeather API can be used for getting weather conditions.

### PR DESCRIPTION
**Pull request by RohanMalik2710**
resolved issue #180

### CODE REVIEW

**Comment by ugpec79** [comment]
@RohanMalik2710 add the html file where the js uses the tags is shown

**Comment by RohanMalik2710** [comment]
> @RohanMalik2710 add the html file where the js uses the tags is shown

Done sir! _Corresponding HTML file is also being reflected in the "Files Changed" section_. Please check

**Comment by ugpec79** [comment]
@RohanMalik2710 Code is not working so review the code and update the pr

**Review by harshjohar — CHANGES_REQUESTED** [review]
did you even run the code locally?

**Comment by RohanMalik2710** [comment]
> did you even run the code locally?

I didn't actually. But now I have corrected it and also ran it on browser. It is running properly now

**Review by harshjohar — CHANGES_REQUESTED** [review]
You should not delete the already merged file. Fix the extra changes by syncing your fork to the main repository and then pulling the forked repo to your local system and commit again

**Comment by ugpec79** [comment]
@RohanMalik2710 one last change is needed in js file the name variable is not working and pls on commiting the file hide ur api key by writing process.env.API

**Comment by ugpec79** [comment]
@RohanMalik2710 since some files have merge conflict in ur pr kindly close this pr and first update ur forked repo and  pull the changes and then commit ur code in new pr

**Pull request closed without merging**
