### PR TITLE
Improved user experience test code ver1.01

### PR DESCRIPTION
**Pull request by thapliyalaryan003**
Is there any other way to specify element number of array in input other than f string. As input( 'Enter the element ' , i1 , 'of array 1') produced error .

### CODE REVIEW

**Comment by abhinavmalhotra01** [comment]
str(i1) should work

**Comment by abhinavmalhotra01** [comment]
LGTM :+1:

**Comment by thapliyalaryan003** [comment]
Thankyou

**Comment by abhinavmalhotra01** [comment]
#201

**Comment by thapliyalaryan003** [comment]
Need to make new pr?

**Comment by abhinavmalhotra01** [comment]
let me ask sir

**Comment by abhinavmalhotra01** [comment]
@thapliyalaryan003 no need

**Pull request merged**
