### PR TITLE
Taking input from command line in Java #147

### LINKED ISSUE #147: Taking input from command line in Java
Whatever @Ishwarendra said in #144 but in java, ez

### PR DESCRIPTION
**Pull request by Dharya4242**
Resolved #147

### CODE REVIEW

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
You need take input from command line arguments not like this, see the issue again

**Comment by Dharya4242** [comment]
> You need take input from command line arguments not like this, see the issue again

Sir i have updated the code please check it again and tell me if its correct

**Comment by ken1000minus7** [comment]
The input's correct but u were asked to print the max value, not all the values

**Comment by Dharya4242** [comment]
> The input's correct but u were asked to print the max value, not all the values

okay sir I thought we have to print the values,
i will make changes

**Comment by Dharya4242** [comment]
> The input's correct but u were asked to print the max value, not all the values

done sir

**Comment by ken1000minus7** [comment]
Code looks good, remove the .class file though

**Comment by Dharya4242** [comment]
> Code looks good, remove the .class file though

.class mere laptop se toh delete mar di thi but pta nhi kyu nhi horhi github pr

**Comment by ken1000minus7** [comment]
hv u committed and pushed after deleting the file

**Comment by Dharya4242** [comment]
> hv u committed and pushed after deleting the file

yes sir, i think vs code loading kr rha hai commit walle section pr clock bni hui hai

**Comment by harshjohar** [comment]
send a screenshot or come to discord chat

**Comment by Dharya4242** [comment]
> send a screenshot or come to discord chat

image

**Comment by Dharya4242** [comment]
> send a screenshot or come to discord chat

discord pr konse section ya chat pr ana hai?

**Comment by harshjohar** [comment]
Screenshot 2023-03-05 at 1 12 58 AM
click on this button in the bottom bar

**Comment by Dharya4242** [comment]
kuch nhi hua

**Comment by ken1000minus7** [comment]
run the command `git push origin main`

**Comment by Dharya4242** [comment]
I think hogya commit, clock wala symbol chla gya please check it again sir

**Review by ken1000minus7 — APPROVED** [review]
Lgtm

**Pull request merged**
