### PR TITLE
Find the Winner #151

### LINKED ISSUE #151: Find the winner
# CP

## Problem Statement 
One day,  Zoro decided to have a look at the scores of the finals of the PEC football tournament (only 2 teams can play finals 🤓) , but he is not good at maths and needs your help. You are provided with the count of the total number of goals made in the match and the name of the team that scored the corresponding goal. The team with the maximum number of goals will win. Kindly help Zoro 😇  

### Input Format -
First Line contains a single integer , the total number of goals in the match. The following n lines contain a string denoting the name of team that scored the ith goal. 

### Output Format - 
A string denoting the name of the winner team

### Constraints -
1<= n <= 100
1<= team_name.size() <= 10 (the size of the team name string will not exceed 10 and string will be in uppercase always)

### Example -
Input :
5
A
ABA
ABA
A
A

Output :
A

### Explanation -
Team with name 'A' scored 3 goals , whereas team with name 'ABA' scored 2 goals and hence , team 'A' was the winner

### PR DESCRIPTION
**Pull request by Prajwa-l-Kumar**
Solved Issue #151

### CODE REVIEW

**Comment by Ishwarendra** [comment]
@Prajwa-l-Kumar Delete `PolyCarp.java` and then wait until this PR gets merged (or learn about how to PR using branches).

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
U r not updating the `maxScore`
ur code is failing this testcase
```
5
a
ab
ab
a
a
```

**Comment by Prajwa-l-Kumar** [comment]
I updated and commited the file in my forked repo. Do I need to create another pull request now, or are the commits covered in this PR itself?

**Comment by ken1000minus7** [comment]
The commits are added to this pr itself, no need to make a new on

**Review by ken1000minus7 — APPROVED** [review]
Lgtm

**Pull request merged**
