### PR TITLE
Write a command line application for tic-tac-toe 

### LINKED ISSUE #132: Write a command line application for tic-tac-toe
Your application should
- display a 3x3 empty board first
- asks user for input (in terms of cell number) -- labelled through 0 to 8 or 1 to 9
- asks alternatively for O and X
- stops whenever either wins and greets the winner

### PR DESCRIPTION
**Pull request by GauravGupta993**
#132

### CODE REVIEW

**Comment by ken1000minus7** [comment]
Hey @GauravGupta993 pls don't make a pr to an issue u r not assigned to, I understand that this issue is not assigned to anyone else but since that's the case u need to atleast ask to be assigned before making a pr, the thing is if u r assigned to the issue then noone else would waste their time trying to solve it, for now comment on the issue asking to be assigned and then we'll review ur pr

**Comment by Ishwarendra** [comment]
This is a python code, not a CLI application. Please read about how to make CLI application using python (or use some other language).

**Comment by Ishwarendra** [comment]
Hi @GauravGupta993, this is not a CLI application. You need to make a `exe` file so it runs on any computer without the need of installing compiler/interpretor for that programming language. 
Check @ken1000minus7 comment too. Next time, we see any PR on issues **not** assigned to you, we will simply close it even if it's correct. Take care about that.

**Comment by GauravGupta993** [comment]
> Hey @GauravGupta993 pls don't make a pr to an issue u r not assigned to, I understand that this issue is not assigned to anyone else but since that's the case u need to atleast ask to be assigned before making a pr, the thing is if u r assigned to the issue then noone else would waste their time trying to solve it, for now comment on the issue asking to be assigned and then we'll review ur pr

Yes sir, I will not repeat the same next time. I had a misunderstanding that we can create multiple PR through branching if it is not assigned to someone.will take care from next time.

**Comment by GauravGupta993** [comment]
> Hi @GauravGupta993, this is not a CLI application. You need to make a `exe` file so it runs on any computer without the need of installing compiler/interpretor for that programming language. 
> Check @ken1000minus7 comment too. Next time, we see any PR on issues **not** assigned to you, we will simply close it even if it's correct. Take care about that.

Yes sir, I will create PR only to those issues assigned to me.

**Comment by GauravGupta993** [comment]
I just added a .exe file for the same through commit. Please confirm if it is what is asked in the question or not. I made it by installing "pip install pyinstaller". Unable to find any other method to create a .exe file from a .py file.

**Review by Ishwarendra — CHANGES_REQUESTED** [review]
Sorry for delay.. You should restrict user to fill only unfilled positions only. @GauravGupta993

**Comment by GauravGupta993** [comment]
Windows PowerShell 06-03-2023 22_14_53

**Comment by Ishwarendra** [comment]
LGTM @GauravGupta993

**Pull request merged**
