### PR TITLE
PWOC OP

### LINKED ISSUE #19: PWOC OP
# CP
Alice and Bob have been competitors for a long time. Now they have decided to compete in the PEC Winter Of Code (PWOC). Obviously, both of them want to win PWOC and get the prize money. To win, they both must get the maximum points possible. The person with higher points will win PWOC. 

There are $3$ types of problems available in PWOC. They are easy, medium, and hard. Easy questions will provide $2$ points, medium questions will provide $4$ points and hard problems will provide $6$ points. They will pick the questions one by one. A coin will be tossed to decide which player will pick the questions first.  If the coins show 'Tails', Alice will choose the question first otherwise Bob will choose first. They both will have alternate turns.

---

**Input Format**
The first line contains an integer N, the number of problems. The second line contains the output of coin, 'H' means head and 'T' means tails. The third line contain N characters E, M, H, where E refers to Easy question, M refers to medium question and H refers to hard question.

**Output Format**
Print "Alice" if Alice wins otherwise print "Bob".

**Sample Input 1**
5
T
H E M H M

**Sample Output**
Alice

### PR DESCRIPTION
**Pull request by GauravGupta993**
Resolved #19

### CODE REVIEW

**Review by Modernbeast02 — CHANGES_REQUESTED** [review]
This code is failing on the test case-
5
T
E H E H E

Your Output - Bob
Correct Answer - Alice.

If you don't understand why the Correct answer is Alice, u can ping me on discord.

**Comment by Modernbeast02** [comment]
@GauravGupta993 Alice can first pick the issue at index 1, then Bob can pick the issue at index 3. Then Alice can pick the issue at index 0 and Bob can pick the issue at index 2. In the end, Alice will take issue at index 4. Total Alice points - 10, Bob points - 8. So Alice wins. The issues can be taken in any order :)

**Comment by GauravGupta993** [comment]
> @GauravGupta993 Alice can first pick the issue at index 1, then Bob can pick the issue at index 3. Then Alice can pick the issue at index 0 and Bob can pick the issue at index 2. In the end, Alice will take issue at index 4. Total Alice points - 10, Bob points - 8. So Alice wins. The issues can be taken in any order :)

**Comment by GauravGupta993** [comment]
> @GauravGupta993 Alice can first pick the issue at index 1, then Bob can pick the issue at index 3. Then Alice can pick the issue at index 0 and Bob can pick the issue at index 2. In the end, Alice will take issue at index 4. Total Alice points - 10, Bob points - 8. So Alice wins. The issues can be taken in any order :)

In this case, I think it does not even matter how many problems are there or what type of problems are there and it will only depend on the first coin toss. Because if tails come, then Alice will always be the winner(because it is assumed that they can solve the problem of any difficulty correctly) or it may end up in draw which is not in the options of possible output. Since she is given the first choice to select the question, she will always choose the question with the most points which will take her total points more than bob. Also if head comes, bob will also always be the winner. Please tell me if this is correct or not.

**Comment by Modernbeast02** [comment]
> > @GauravGupta993 Alice can first pick the issue at index 1, then Bob can pick the issue at index 3. Then Alice can pick the issue at index 0 and Bob can pick the issue at index 2. In the end, Alice will take issue at index 4. Total Alice points - 10, Bob points - 8. So Alice wins. The issues can be taken in any order :)
> 
> In this case, I think it does not even matter how many problems are there or what type of problems are there and it will only depend on the first coin toss. Because if tails come, then Alice will always be the winner(because it is assumed that they can solve the problem of any difficulty correctly) or it may end up in draw which is not in the options of possible output. Since she is given the first choice to select the question, she will always choose the question with the most points which will take her total points more than bob. Also if head comes, bob will also always be the winner. Please tell me if this is correct or not.



> > @GauravGupta993 Alice can first pick the issue at index 1, then Bob can pick the issue at index 3. Then Alice can pick the issue at index 0 and Bob can pick the issue at index 2. In the end, Alice will take issue at index 4. Total Alice points - 10, Bob points - 8. So Alice wins. The issues can be taken in any order :)
> 
> In this case, I think it does not even matter how many problems are there or what type of problems are there and it will only depend on the first coin toss. Because if tails come, then Alice will always be the winner(because it is assumed that they can solve the problem of any difficulty correctly) or it may end up in draw which is not in the options of possible output. Since she is given the first choice to select the question, she will always choose the question with the most points which will take her total points more than bob. Also if head comes, bob will also always be the winner. Please tell me if this is correct or not.

That is Correct.

**Comment by GauravGupta993** [comment]
I changed the code. Is it correct now?

**Comment by Modernbeast02** [comment]
Lgtm, GW

**Pull request merged**
