### PR TITLE
Reloved issue #54

### PR DESCRIPTION
**Pull request by himanshusab12**
Completed the Issue- Return count of number of occurrences of a number in a numpy array

### CODE REVIEW

**Comment by abhinavmalhotra01** [comment]
hello ; we only need the file of count occurences for #54 , so please remove others

**Comment by himanshusab12** [comment]
sir, the topmost file is of this issue -  https://github.com/PEC-CSS/graveyard/pull/74/commits/ca64dad385a341230cf3ff2d5ec97393eedb3ff3

**Comment by abhinavmalhotra01** [comment]
yes , thats fine , but delete the other files , since they are related to different issues ; 
making a new branch for every issue is better

**Comment by himanshusab12** [comment]
Sir, I created different branch for different issues. But, still all files are being shown here

**Comment by abhinavmalhotra01** [comment]
ohk , you can also delete the files here only ; go in files changed sections ; select the irrelevant files and del them

**Comment by ken1000minus7** [comment]
#94

**Comment by abhinavmalhotra01** [comment]
@himanshusab12 one file left , usko bhi krdo

**Comment by abhinavmalhotra01** [comment]
lgtm 👍

**Pull request merged**
