### PR TITLE
love for cricket solved in python

### LINKED ISSUE #45: Solve "Love For Cricket"
# CP
The problem statement is given [here](https://www.hackerrank.com/contests/codecode-pec/challenges/love-for-cricket). Go ahead and write code for this and submit it as well.

Share screenshot showing all testcases or not. PR will be merged only if all testcases pass.

### PR DESCRIPTION
**Pull request by devikasood**
Screenshot 2023-03-01 at 11 05 38 PM

### CODE REVIEW

**Review by harshjohar — CHANGES_REQUESTED** [review]
logic seems correct, but there are some problems which are causing this: 

Screenshot 2023-03-02 at 1 06 01 AM

1. You don't have to make any `if` checks for given constraints. (this is not causing any wrongs answer tho)
2. while taking `input` or writing `output`, you don't have to write extra messages in CP.

Just print the answer without any prompt.

Screenshot 2023-03-02 at 1 07 53 AM

Check the expected output. Now just edit the file accordingly and commit again, you don't need to make pull request again.

**Comment by ken1000minus7** [comment]
in a question constraints refer to the range in which input will be given, so actually u do not need to check if the input follows the constraints, u just have to assume that the input will be within the given constraints, as u will start solving dsa problems you'll see that based on constraints, our solution can change as for example if the constraints say that the input can be very large, it means that we have to think of an optimized solution

**Comment by devikasood** [comment]
> logic seems correct, but there are some problems which are causing this:
> 
> Screenshot 2023-03-02 at 1 06 01 AM
> 
> 1. You don't have to make any `if` checks for given constraints. (this is not causing any wrongs answer tho)
> 2. while taking `input` or writing `output`, you don't have to write extra messages in CP.
> 
> Just print the answer without any prompt.
> 
> Screenshot 2023-03-02 at 1 07 53 AM
> 
> Check the expected output. Now just edit the file accordingly and commit again, you don't need to make pull request again.

got it! will do

**Comment by devikasood** [comment]
> in a question constraints refer to the range in which input will be given, so actually u do not need to check if the input follows the constraints, u just have to assume that the input will be within the given constraints, as u will start solving dsa problems you'll see that based on constraints, our solution can change as for example if the constraints say that the input can be very large, it means that we have to think of an optimized solution

okay sir got it!

**Review by harshjohar — APPROVED** [review]

**Pull request merged**
