### PR TITLE
Find X

### LINKED ISSUE #149: Find X
### Find X
<hr>

Find a number x such that x<sup>2</sup>+√x=c

**Input Format**

The input contains one real number c

**Constraints**

1.0≤c≤10<sup>10</sup>

**Output Format**

Print one number, the required x. The answer will be considered correct if the relative or absolute error is not more than 10<sup>-6</sup>

**Sample Input** 

10

**Sample Output** 

2.881410786256594303

### PR DESCRIPTION
**Pull request by ParasBisht2003**
Find X #170

### CODE REVIEW

**Comment by harshjohar** [comment]
mention the issue number in pr comment

**Comment by Ishwarendra** [comment]
Delete `.vscode/` dir rest is ok @ParasBisht2003

**Comment by ken1000minus7** [comment]
@ParasBisht2003 updates?

**Comment by ParasBisht2003** [comment]
> @ParasBisht2003 updates?

Sir I've already solved the issue , FindX.java contains the solution, however for some reason .vscode file also got added and now I have no clue how to remove it

**Comment by ken1000minus7** [comment]
Just delete the folder and make a commit

**Comment by ken1000minus7** [comment]
@ParasBisht2003

**Pull request merged**
