### PR TITLE
Solved Nobody Likes To Divide

### LINKED ISSUE #176: Nobody Likes To Divide
You are given an array of 𝑛 positive integers 𝑎1,𝑎2,…,𝑎𝑛. In one operation, you can choose any number of the array and add 1 to it.
Make at most 2𝑛 operations so that the array satisfies the following property: $a_i + 1$ is not divisible by $a_i$, for each 𝑖=1,2,…,𝑛−1.
You do not need to minimize the number of operations.

**INPUT**
The first line contains an integer 𝑛 (1≤𝑛≤ $10^4$) — the length of the given array.
The second line contains 𝑛  integers 𝑎1,𝑎2,…,𝑎𝑛 (1≤ $a_i$ ≤ $10^9$) — the given array.

**OUTPUT**
print 𝑛 integers — the resulting array 𝑎 after applying at most 2𝑛 operations.

**SAMPLE INPUT**
4
2 4 3 6
**SAMPLE OUTPUT**
4 5 6 7

**Explanation**
the array [4,5,6,7] can be achieved by applying 2 operations to the first element, 1 operation to the second element, 3 operations to the third element, and 1 operation to the last element. The total number of operations performed is 7, which is less than the allowed 8 operations in this case.

### PR DESCRIPTION
**Pull request by himanshusab12**
Completed #176

### CODE REVIEW

**Comment by abhinavmalhotra01** [comment]
hello 👋
1. a[i] can go upto 1e9 ( integer overflow)
2. in question , we need to make `a[i+1]%a[i]=!0` not a[i]+1 (a[i]+1 is always not divisble by a[i] (unless a[i]=1) )
3. your code is failing for `a = {2,2,2}` , output is `{4,4,4}` which is incorrect 

try to work on this🙏 
(also , resolve the conflicts)

**Comment by himanshusab12** [comment]
I have updated the code please check

**Comment by abhinavmalhotra01** [comment]
vro , i>0 condition ko if ke bahar ek aur if mei daaldo , to avoid runtime error , 
in the current code , %a[i-1] will be done , leading to runtime error , since the condition inside if is also evaluated first

and the check thing is wrong , since , an operation is counted when a[i]++ , so it is once done outside and once when the condition is true , and since it can be max 2*n only , so you can even remove it . 

aur conflicts bhi krdo 😢

**Comment by abhinavmalhotra01** [comment]
@himanshusab12 hello vro , any updates ?

**Pull request closed without merging**
