### PR TITLE
#83, dsa, solved, leetcode accepttance ss attached

### LINKED ISSUE #83: Shortest Distance to Target String in a Circular Array
You are given a 0-indexed circular string array words and a string target. A circular array means that the array's end connects to the array's beginning.

+ Formally, the next element of words[i] is words[(i + 1) % n] and the previous element of words[i] is words[(i - 1 + n) % n], where n is the length of words.

Starting from startIndex, you can move to either the next word or the previous word with 1 step at a time.

Return the shortest distance needed to reach the string target. If the string target does not exist in words, return -1.

Leetcode link : https://leetcode.com/problems/shortest-distance-to-target-string-in-a-circular-array/

Attach accepted screenshot to PR.

### PR DESCRIPTION
**Pull request by devikasood**
Screenshot 2023-03-03 at 1 10 59 AM

### CODE REVIEW

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
Your code is incorrect, the reason it shows accepted is because u hv run your code only on sample testcases, submit your code and you'll get a wrong answer as then your code will be run on the rest of the testcases

**Comment by devikasood** [comment]
Screenshot 2023-03-03 at 2 21 27 AM

**Comment by devikasood** [comment]
> Your code is incorrect, the reason it shows accepted is because u hv run your code only on sample testcases, submit your code and you'll get a wrong answer as then your code will be run on the rest of the testcases

now I have resolved, submitted, and attached the ss as well..

**Review by ken1000minus7 — APPROVED** [review]
Lgtm, also u can check out other's solution for this question, you'll learn about a more simpler approach

**Comment by devikasood** [comment]
> Lgtm, also u can check out other's solution for this question, you'll learn about a more simpler approach

Okay!! Will do.. thanks

**Pull request merged**
