### PR TITLE
Issue24

### LINKED ISSUE #24: Write HTML/CSS and replicate the given target image in the least code possible.
#CSS

### PR DESCRIPTION
**Pull request by AkankshaNarula**
Resolved Issue #24

### CODE REVIEW

**Review by ken1000minus7 — APPROVED** [review]
Code lgtm, great work, just from next time make the title of the pr describe what u hv done instead of just writing issue24

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
The html file should be inside the web folder

**Comment by AkankshaNarula** [comment]
okk ty will surely keep that in mind next time

**Comment by AkankshaNarula** [comment]
Also should I make the pull request again as changes are requested?

**Comment by NandiniGera** [comment]
> Also should I make the pull request again as changes are requested?

you can commit changes in this pull request itself, no need to create a new one.

**Comment by AkankshaNarula** [comment]
@NandiniGera I believe the changes are approved now as I had already made the file in web folder

**Comment by ken1000minus7** [comment]
It's still outside, hv u committed and pushed the new changes?

**Comment by NandiniGera** [comment]
> @NandiniGera I believe the changes are approved now as I had already made the file in web folder

The commited file is not in the web folder. Change its path and commit and push the changes again.

**Comment by AkankshaNarula** [comment]
@ken1000minus7 @NandiniGera Pls check it now

**Comment by NandiniGera** [comment]
> @ken1000minus7 @NandiniGera Pls check it now

One pull request has to be for one issue only.  Remove the issue 56 file for now ( keep the code copied with you) and after this pr has been merged, then commit and push file for issue 56 and create another pr with description- Resolved issue #56 .  Don't add commits for another issue in the same pr.

**Comment by AkankshaNarula** [comment]
@NandiniGera I had already removed the issue56 file when I changed the path and will make another pull request for it

**Pull request closed without merging**
